### ISSUE TITLE
似乎在windows上容易出问题

### ISSUE THREAD

**Issue by xingdongzhe** [the5fire/typeidea#10]
我使用win10+python3.7
在安装依赖库的时候出现了问题，supervisor==4.0.0dev0(不存在，另外supervisor不支持python3)

**Comment by the5fire** [comment]
@XingDongZhe  现在 supervisor 可以直接用最新版了，已经支持 Python 3 了。之前用是开发版。

**Comment by xingdongzhe** [comment]
thank you
