### ISSUE TITLE
pycharm import错误提示

### ISSUE THREAD

**Issue by flyerooo** [the5fire/typeidea#12]
Django2.2
![image](https://user-images.githubusercontent.com/6385820/57243744-6fbc5000-7069-11e9-99e3-6cd15d7f9b04.png)
这样导入pycharm会有错误提示
应该是Pycharm设置的问题，是否有人能分享一下pycharm配置

**Comment by the5fire** [comment]
把 typeidea 的目录加到 pycharm 的 path 配置里试试

**Comment by MaoningGuan** [comment]
这个报错关系不大，代码能跑。这个只是pycharm根据自己的规则提示的错误，不是代码的问题。
