### ISSUE TITLE
book/06-admin : 有几个问题请教下作者

### ISSUE THREAD

**Issue by neusofzsjt** [the5fire/typeidea#13]
您好，有几个疑惑请教下：
1、blog/admin中的PostAdmin类下，save_on_top出现了两次，是否是重复冗余的代码？
2、blog/admin中的PostAdmin类下，exclude = ['owner',]，这行代码在基类BaseOwnerAdmin中已经提取，这里的是否可以去除？
3、书中P122页的filter_vertical或者filter_horizontal的字段写成tags了，应该是tag的
4、我在PostAdmin引用自定义Form的时候，抛异常，显示自定义的Form没有指明Model，我指明了相关的Model之后，才能正常运行，但是我看您的代码是不用指明的，跟着您的代码重敲了一遍之后又可以了。所以有个问题，自定义Form的Model不用指明是因为装饰器已经把admin和Model和Form三个绑定在一起了吗？

**Comment by the5fire** [comment]
@neusofzsjt 感谢！

勘误可以看这里：https://www.the5fire.com/987.html 

第 4 点：不指定 Form 对应的 Model 的情况下， Admin 会处理。
