### ISSUE TITLE
12章 报错

### ISSUE THREAD

**Issue by Moebyte** [the5fire/typeidea#15]
~~作者你好，我在写完12章的代码后，运行程序，编辑文章时，发现无法选择标签和分类，以下时错误反馈
Response to request with pk 2a2983f1-6dad-472b-a6eb-29542c2af75a has content type text/javascript but was unable to parse it
[19/Jun/2019 06:54:21] "GET /admin/jsi18n/ HTTP/1.1" 200 7722~~

Django版本的问题

**Comment by DaedalusT** [comment]
我退回第10章也发现了这个问题，编辑文章无法选择分类和标签
