### ISSUE TITLE
?: (urls.E007) The custom handler500 view 'blog.views.Handler50x' does not take the correct number of arguments (request).

### ISSUE THREAD

**Issue by zanone** [the5fire/typeidea#16]
?: (urls.E007) The custom handler500 view 'blog.views.Handler50x' does not take the correct number of arguments (request).

**Comment by the5fire** [comment]
可能是你少写了一个括号？

` handler500 = Handler50x.as_view()`

 写了篇文章：https://www.the5fire.com/django-error-handler-source-code.html
帮助你更好的解决问题。

**Comment by shahramsamar** [comment]
handler500 (server error) requires a view with only the request parameter.
handler404 (not found) requires request and exception parameters.
in view:
from django.shortcuts import render
def error_500(request):
    return render(request, '500.html', status=500)
urls:
from django.conf.urls import handler500
handler500 = 'website.views.base.error_500'
