### ISSUE TITLE
./manage.py makemigrations 错误问题，

### ISSUE THREAD

**Issue by aladdingsw** [the5fire/typeidea#21]
使用./manage.py makemigrations 错误问题，后出现ModuleNotFoundError: No module named 'typeidea.typeidea'
错误

<img width="512" alt="图片" src="https://user-images.githubusercontent.com/51047000/61578724-5a65a680-ab2d-11e9-972b-b9556834d8fd.png">

**Comment by sailorlisa** [comment]
图片挂了，可以重新发图片吗？或者贴代码？

**Comment by xueanguo** [comment]
ModuleNotFoundError: No module named 'typeidea.blog'

**Comment by the5fire** [comment]
@sailorlisa  不应该出现 `typeidea.typeidea` 这样的引用。贴下你的 settings/base.py 或者  settings.py 看看。

@xueanguo   也可以贴一下。

**Comment by sailorlisa** [comment]
我的settings/base.py ↓
https://github.com/sailorlisa/typeidea/blob/master/typeidea/typeidea/settings/base.py

@aladdingsw 请去链接参考。

**Comment by MaoningGuan** [comment]
ModuleNotFoundError: No module named 'typeidea.blog'

ModuleNotFoundError: No module named 'typeidea.typeidea'
***
**这些引用路径直接改为：**
```python
'typeidea.blog' --->  'blog'
'typeidea.typeidea' ----> 'typeidea'
```
直接从APP的目录开始引用就可以了。
