### ISSUE TITLE
p330 "在线上数据库中，我们一般会去掉外键约束，以提升性能"

### ISSUE THREAD

**Issue by flyerooo** [the5fire/typeidea#24]
"在线上数据库中，我们一般会去掉外键约束，以提升性能"
请问这个是只需要这样设置就可以吗？

 在setting设置
```py
'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
```

**Comment by the5fire** [comment]
你是不是在群里问过我这个问题了 ^.^

不一样的逻辑。这个只是针对当前会话生效，并且也只是对于我们应用生效。

想一下数据库的使用场景，不仅是我们的应用中。
