### ISSUE TITLE
makemigrations/makemigrate/dbshell命令无效，请胡老师看下什么问题

### ISSUE THREAD

**Issue by arthur-wxy** [the5fire/typeidea#47]
如图，按照书中的`./manage.py makemigrations`执行会报错，查了下需要用`python3 manage.py makemigrations `可是此命令没有任何反应，麻烦老师看下什么原因
<img width="1440" alt="Screen Shot 2020-06-18 at 9 43 42 AM" src="https://user-images.githubusercontent.com/39916187/84968320-cb03b180-b148-11ea-9642-6eaa26793b10.png">

**Comment by arthur-wxy** [comment]
我的版本
Python v3.8.3
Django v3.0.7

**Comment by MaoningGuan** [comment]
python manage.py makemigrations

**Comment by arthur-wxy** [comment]
> python manage.py makemigrations

这个命令跟 `./manage.py makemigrations` 报错一样：

  File "manage.py", line 23
    ) from exc
         ^
SyntaxError: invalid syntax

**Comment by MaoningGuan** [comment]
这是提示了manage.py的line 23那里的语法错误，你那行代码：
```python
execute_from_command_line(sys.argv)
```
缩进多了，这行代码跟try...except同级。
![image](https://user-images.githubusercontent.com/20440158/84972777-28e8c700-b152-11ea-8c50-4581a4bcbb1d.png)

**Comment by MaoningGuan** [comment]
我的Django版本跟你的不一样，except里面实现不一样，不过原理是一样的。
都是获取命令行参数，传给execute_from_command_line函数调用。

**Comment by arthur-wxy** [comment]
> 我的Django版本跟你的不一样，except里面实现不一样，不过原理是一样的。
> 都是获取命令行参数，传给execute_from_command_line函数调用。

好的解决了，谢谢～
