### ISSUE TITLE
python3 manage.py makemigrations 时提示no changes detectd

### ISSUE THREAD

**Issue by arthur-wxy** [the5fire/typeidea#48]
`python3 makemigrations `提示no changes detected
 于是`python3 manage.py makemigrations blog` 报错：No installed app with label 'blog'.
<img width="1440" alt="Screen Shot 2020-06-18 at 8 45 17 PM" src="https://user-images.githubusercontent.com/39916187/85022185-8a865100-b1a5-11ea-95ee-5f47aeb83c95.png">

django v3.0.7

麻烦老师看看怎么解决这个问题

**Comment by MaoningGuan** [comment]
其实pycharm里面提示的错误已经很明显了。
no changes detected：
你的model定义没有更改。
No installed app with label 'blog'：
在setting里面没有配置blog这个APP，django找不到这个APP

**Comment by arthur-wxy** [comment]
> 其实pycharm里面提示的错误已经很明显了。
> no changes detected：
> 你的model定义没有更改。
> No installed app with label 'blog'：
> 在setting里面没有配置blog这个APP，django找不到这个APP

<img width="1440" alt="Screen Shot 2020-06-21 at 9 42 09 AM" src="https://user-images.githubusercontent.com/39916187/85214875-8a53a480-b3a3-11ea-87c2-f090fbc810e8.png">
其实我是配置的 setting/base.py里面

**Comment by arthur-wxy** [comment]
<img width="1440" alt="Screen Shot 2020-06-21 at 9 59 46 AM" src="https://user-images.githubusercontent.com/39916187/85215091-27174180-b3a6-11ea-8ea1-a39eee0d20b7.png">
是manage.py里代码有问题，读不到setting/base.py里的配置吗？

**Comment by MaoningGuan** [comment]
你的develop.py有没有导入base.py里面的配置？
```python
from .base import * 
```

**Comment by arthur-wxy** [comment]
<img width="1440" alt="Screen Shot 2020-06-21 at 7 13 22 PM" src="https://user-images.githubusercontent.com/39916187/85224442-00382a00-b3fd-11ea-8819-55e330a47f2c.png">
有导入的

**Comment by MaoningGuan** [comment]
```python
python manage.py makemigrations comment config
```
试一下另外两个APP可以用吗？

**Comment by arthur-wxy** [comment]
<img width="1440" alt="Screen Shot 2020-06-22 at 6 40 04 PM" src="https://user-images.githubusercontent.com/39916187/85278730-e4de2500-b4b7-11ea-9148-c365b14ef121.png">
`File "/Users/arthurw/PycharmProjects/typeidea/typeidea/blog/models.py", line 17, in Category
    owner = models.ForeignKey(User, verbose_name="作者")
TypeError: __init__() missing 1 required positional argument: 'on_delete'`

现在报这个了

**Comment by MaoningGuan** [comment]
```python
owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
```

**Comment by arthur-wxy** [comment]
> ```python
> owner = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
> ```

已解决 谢谢老师，查了是Django的版本 必须加上这个on_delete

**Comment by MaoningGuan** [comment]
是的，旧版本的Django会默认帮我们设置on_delete参数为CASCADE：
![image](https://user-images.githubusercontent.com/20440158/85357315-9d04df80-b543-11ea-8293-f42fc78b9612.png)
