### ISSUE TITLE
关于配置纯展示页面遇到的问题

### ISSUE THREAD

**Issue by weepelf0** [the5fire/typeidea#53]
老师您好，目前尝试使用Django开发一套企业官网，其中我想把首页作为一个纯展示页面，
结果遇到报错内容：
TemplateDoesNotExist at /hp
且对应路径报错提示：
Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.filesystem.Loader: /Users/我的用户名/Documents/我的项目名/templates/config/index.html (Source does not exist)#（路径是项目真是存在的路径，html文件也存在，但是出现了这个报错）
------

我的项目中config作为一个app，其中的views.py内容如下：
#省略其他代码
def index_hp(request,index_id=None):
index = Index.objects.get()
return render(request,'config/index.html',context={'name':index})
------

项目中settings.py 
#省略其他代码
TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [os.path.join(BASE_DIR, 'templates/')], #（感觉这个BASE_DIR路径会不会要改写？？）
'APP_DIRS': True,
'OPTIONS': {
'context_processors': [
'django.template.context_processors.debug',
'django.template.context_processors.request',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]
#省略其他代码
INSTALLED_APPS = [
'article',
'case',
'config',(这个是app名称)

'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
]

------

项目中urls.py配置 ...
from django.urls import re_path,path
#省略其他代码
from config.views import index_hp
#省略其他代码
urlpatterns = [
path('hp',index_hp,name='首页'),
]
------

然后就出现了上面描述的错误，
如果老师方便的话，还请指导一下，
先谢过！

**Comment by MaoningGuan** [comment]
找不到config/index.html这个文件的路径，你检查一下'DIRS': [os.path.join(BASE_DIR, 'templates/')]，这里的路径是否设置正确。
![image](https://user-images.githubusercontent.com/20440158/89606355-4f99c300-d8a2-11ea-89d3-1fbf9740bb9e.png)
你可以看这些错误提示信息，看django加载templates文件的路径是否是你设置的路径。

**Comment by weepelf0** [comment]
非常感谢老师抽空回复，目前这个问题得到了解决；
可能因为我使用的是Django3.0版本，vscode中配置了anaconda虚拟环境，以及macOS系统的原因，
目前解决的办法是通过手写'DIRS': [os.path.join(BASE_DIR, 'templates/')]中【BASE_DIR】替换为本地的绝对路径，
重新运行后可以正确加载本地的样式文件了。
（因为初次使用github，问题本身的排版比较丑，再次感谢老师的耐心阅读和解答）
