### ISSUE TITLE
'User' object is not iterable

### ISSUE THREAD

**Issue by scor-pan** [the5fire/typeidea#7]
你好，请问这个问题可能由哪些原因造成？

Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/blog/post/add/?_to_field=id&_popup=1
Django Version:	1.11.20
Exception Type:	TypeError
Exception Value:	
'User' object is not iterable
Exception Location:	/home/pan/桌面/typeidea-env/lib/python3.6/site-packages/django/utils/functional.py in inner, line 239
Python Executable:	/home/pan/桌面/typeidea-env/bin/python
Python Version:	3.6.7
Python Path:	
['/home/pan/桌面/typeidea/typeidea',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/home/pan/桌面/typeidea-env/lib/python3.6/site-packages']

**Comment by the5fire** [comment]
@scor-pan 你这个得上代码才能看出问题

**Comment by the5fire** [comment]
先关掉了，如果还有问题可以重新打开。
